#!/usr/bin/env bash

# GitHub Repository Browser
#
# Author: Generated by Claude
# Purpose: Browse GitHub repositories by organization and topic
# Dependencies: curl, jq
# Date: 2024

# Error handling
set -euo pipefail
trap 'echo "Error: Script failed on line $LINENO"' ERR

# Check dependencies
check_dependencies() {
    local deps=("curl" "jq")
    for dep in "${deps[@]}"; do
        if ! command -v "$dep" >/dev/null 2>&1; then
            echo "Error: Required dependency '$dep' is not installed."
            exit 1
        fi
    done
}

# Validate environment
check_env() {
    if [[ ! -f .env ]]; then
        echo "Error: .env file not found"
        exit 1
    fi

    # Source .env file
    source .env

    if [[ -z "${GITHUB_TOKEN:-}" ]]; then
        echo "Error: GITHUB_TOKEN not set in .env file"
        exit 1
    fi
}

# GitHub API request function
github_request() {
    local endpoint="$1"
    curl -s -H "Authorization: token $GITHUB_TOKEN" \
         -H "Accept: application/vnd.github.v3+json" \
         "https://api.github.com$endpoint"
}

# Display repositories
display_repos() {
    local org="$1"
    local topic="$2"

    echo "Fetching repositories for org '$org' with topic '$topic'..."
    
    # Get repositories for organization with topic
    local repos
    repos=$(github_request "/search/repositories?q=org:$org+topic:$topic" | \
            jq -r '.items[] | "\(.name) | Stars: \(.stargazers_count) | \(.description)"')

    if [[ -z "$repos" ]]; then
        echo "No repositories found."
        return
    fi

    echo -e "\nFound repositories:"
    echo "===================="
    echo "$repos" | nl
}

# Main menu
main_menu() {
    while true; do
        echo -e "\nGitHub Repository Browser"
        echo "======================="
        echo "1. Search repositories"
        echo "2. Exit"
        
        read -rp "Select an option: " choice

        case $choice in
            1)
                read -rp "Enter organization name: " org
                read -rp "Enter topic: " topic
                display_repos "$org" "$topic"
                ;;
            2)
                echo "Goodbye!"
                exit 0
                ;;
            *)
                echo "Invalid option"
                ;;
        esac
    done
}

# Main execution
main() {
    check_dependencies
    check_env
    main_menu
}

main 